"""
Stub file was autogenerated by `python3 manage.py startproject website`.

This file specifies which models in model.py are accessible from Django's
builtin admin web interface.
"""
from django.contrib import admin

# Register your models here.
