"""
Stub file was autogenerated by `python3 manage.py startproject website`.

This file specifies which models in model.py are accessible from Django's
builtin admin web interface.
"""
from django.contrib import admin

from .models import *

# Register your models here.
admin.site.register(User)
admin.site.register(Task)
admin.site.register(Container)
admin.site.register(StudySession)
admin.site.register(TaskSession)