"""
File autogenerated by `python3 manage.py startproject website`.

Not sure what this file is for but I haven't had to edit it.
"""
from django.apps import AppConfig


class WebsiteConfig(AppConfig):
    name = 'website'
